services:
  message-server:
    image: padnt:1.0.0
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/logs/tomcat         # Persist Tomcat logs
      - ./database:/database
    restart: always
    container_name: padnt